# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0002_councilman_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=12, verbose_name='Candidate Id')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('candidate', models.CharField(max_length=150, verbose_name='Candidate')),
                ('donor', models.CharField(max_length=255, verbose_name='Donor')),
                ('donor_tax_name', models.CharField(max_length=255, verbose_name='Donor Tax Name')),
                ('economic_sector', models.CharField(max_length=100, verbose_name='Economic Sector')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Value')),
                ('type', models.CharField(max_length=150, verbose_name='Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('councilman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='councilman', to='councilman.Councilman')),
            ],
        ),
    ]
