# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilman',
            name='sequential_id',
            field=models.IntegerField(null=True),
        ),
    ]
