# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0004_councilman_sequential_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='candidate_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='sequential_id',
            field=models.IntegerField(null=True, verbose_name='Sequential Id'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='sequential_id',
            field=models.IntegerField(verbose_name='Sequential Id'),
        ),
    ]
