# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0007_auto_20170331_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilman',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
    ]
