# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0008_auto_20170331_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilman',
            name='sequential_id',
            field=models.BigIntegerField(default=None, null=True, verbose_name='Sequential Id'),
        ),
    ]
