# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0010_auto_20170331_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='type',
            new_name='kind',
        ),
    ]
