# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0011_auto_20170401_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilman',
            name='address',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='biography',
            field=models.TextField(default=None, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='email',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='floor',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='page_link',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Page Link'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='party',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='phone_number',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='picture',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='councilman',
            name='room',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Room'),
        ),
    ]
