# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0013_councilman_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilman',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
