# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0015_auto_20170401_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.BigIntegerField(null=True, verbose_name='Sequential Id')),
                ('kind', models.CharField(max_length=150, verbose_name='Type')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Value')),
                ('election_year', models.IntegerField(verbose_name='Election Year')),
                ('from_file', models.CharField(default=None, max_length=255, null=True, verbose_name='From file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('councilman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilman.Councilman')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('expense', models.CharField(max_length=255, verbose_name='Expense')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Value')),
                ('provider', models.CharField(max_length=255, verbose_name='Provider')),
                ('cnpj', models.CharField(max_length=255, verbose_name='Tax ID')),
                ('sequential_id', models.BigIntegerField(null=True, verbose_name='Sequential Id')),
                ('from_file', models.CharField(default=None, max_length=255, null=True, verbose_name='From file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('councilman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilman.Councilman')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.BigIntegerField(null=True, verbose_name='Sequential Id')),
                ('votes', models.IntegerField(verbose_name='Votes')),
                ('election_year', models.IntegerField(verbose_name='Election Year')),
                ('from_file', models.CharField(default=None, max_length=255, null=True, verbose_name='From file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('councilman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilman.Councilman')),
            ],
        ),
    ]
