# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0016_asset_expense_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Votes',
            new_name='Vote',
        ),
    ]
