# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0017_auto_20170402_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesElection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.BigIntegerField(null=True, verbose_name='Sequential Id')),
                ('provider', models.IntegerField(verbose_name='Provider')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('economic_sector', models.IntegerField(verbose_name='Economic Sector')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('kind', models.IntegerField(verbose_name='Kind')),
                ('description', models.IntegerField(verbose_name='Description')),
                ('from_file', models.CharField(default=None, max_length=255, null=True, verbose_name='From file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('councilman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='councilman.Councilman')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.BigIntegerField(null=True, verbose_name='Sequential Id')),
                ('sector', models.IntegerField(verbose_name='Sector')),
                ('name', models.IntegerField(verbose_name='Name')),
                ('role', models.IntegerField(verbose_name='Role')),
                ('gross_salary', models.IntegerField(verbose_name='Gross Salary')),
                ('net_salary', models.IntegerField(verbose_name='Net Salary')),
                ('as_of', models.IntegerField(verbose_name='As Of')),
                ('link', models.IntegerField(verbose_name='Link')),
                ('download_time', models.IntegerField(verbose_name='Download Time')),
                ('from_file', models.CharField(default=None, max_length=255, null=True, verbose_name='From file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('councilman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='councilman.Councilman')),
            ],
        ),
    ]
