# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('councilman', '0018_expenseselection_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseselection',
            name='cnpj',
            field=models.CharField(max_length=255, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='expenseselection',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='expenseselection',
            name='economic_sector',
            field=models.CharField(max_length=255, verbose_name='Economic Sector'),
        ),
        migrations.AlterField(
            model_name='expenseselection',
            name='kind',
            field=models.CharField(max_length=255, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='expenseselection',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='Provider'),
        ),
    ]
