# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Councilman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('page_link', models.CharField(max_length=100, verbose_name='Page Link')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('floor', models.CharField(max_length=10, verbose_name='Floor')),
                ('room', models.CharField(max_length=10, verbose_name='Room')),
                ('biography', models.TextField(verbose_name='Biography')),
                ('party', models.CharField(max_length=10, verbose_name='Party')),
                ('picture', models.CharField(max_length=255, verbose_name='Picture')),
            ],
        ),
    ]
